import Service, { service } from '@ember/service';
import { computed, get } from '@ember/object';

export default class DealOptionsService extends Service {
  @service store;

  @computed()
  get allBookManagerBanks() {
    const store = this.store;

    return store.findAll('book-manager-bank');
  }

  @computed()
  get allOtherManagerBanks() {
    const store = this.store;

    return store.findAll('other-manager-bank');
  }

  absAssetClass = [
    'Aircraft Receivables',
    'Auto',
    'Consumer Loans',
    'Credit Cards',
    'Diversified Payment Rights',
    'Equipment Leases',
    'Government',
    'Healthcare Receivables',
    'Home Equity',
    'Insurance',
    'Manufactured Housing',
    'Non-performing Loans',
    'Other',
    'Project Finance',
    'Pubs',
    'Student Loans',
    'Whole Business Securitisation',
  ];

  affirmation = ['Yes', 'No'];

  assetClass = ['ABS', 'CDO', 'CMBS', 'MBS'];

  cdoAssetClass = [
    'ABS CDO',
    'Balance Sheet Corporate CLO',
    'CBO',
    'CDO of CDO',
    'CFO',
    'CRE',
    'CSO',
    'Emerging Market CDO',
    'High Grade ABS CDO',
    'Leveraged Loan CLO',
    'Mezzanine ABS CDO',
    'Mezzanine/Hybrid Capital',
    'SME CLO',
    'PFI/PPP CLO',
    'CPDO',
    'CPPI',
    'CDO of Equity Default Swaps',
    'Other',
    'CLO',
    'CAT BONDS',
    'TruPS CDO',
    'RMBS CDO',
    'Investment Grade Synthetic CDO',
  ];

  cdoType = ['Cash', 'Synthetic'];

  collateral = [
    '(use free text)',
    'Adjustable Rate Mortgage Loans',
    'Aircraft Leases',
    'Auto Leases',
    'Auto Loans/Receivables',
    'Boat Loans',
    'Co-Participation Tax Revenue',
    'Commercial Mortgages',
    'Consumer Loans',
    'Credit Card Receivables',
    'Equipment Leases',
    'Farm Equipment Loans',
    'Finance Loans',
    'Home Equity Loans',
    'Home Improvement Loans',
    'Installment Receivables',
    'Manufactured Housing Contracts',
    'Mortgage Loans',
    'Other Receivables',
    'Recreational Vehicle Loans',
    'Residential Mortgages',
    'SBA Loans',
    'Student Loans',
    'Trade Receivables',
    'Truck Loans',
  ];

  couponType = [
    'Fixed',
    'Floating',
    'Step-Up',
    'Zero',
    'PIK',
    'Fixed/Floating',
    'Undisclosed',
  ];

  coveredBonds = [
    'All Covered Bonds',
    'HP German law',
    'OP German law',
    'OF French law',
    'OFH French law',
    'French structured covered bond',
    'CH Spanish law',
    'CT Spanish law',
    'UK regulated covered bond',
    'ACS Irish covered bond',
    'Australian covered bond',
    'Austrian covered bond',
    'Canada mortgage bond',
    'Danish covered bond',
    'Dutch legislative covered bond',
    'Finnish legislative covered bond',
    'Greek covered bond',
    'Hungarian covered bond',
    'Korean covered bond',
    'LdG Lux law',
    'New Zealand covered bond',
    'Norwegian legislative covered bond',
    'OBG Italian law',
    'OH Portuguese law',
    'Swedish legislative covered bond',
    'Swiss covered bond',
    'Swiss structured covered bond',
    'US covered bond',
    'Belgian Pandbrieven',
    'Other',
  ];

  currency = [
    'AED',
    'ALL',
    'AMD',
    'ANG',
    'AOA',
    'ARS',
    'ATS',
    'AUD',
    'AWG',
    'AZM',
    'BAM',
    'BBD',
    'BDT',
    'BGN',
    'BHD',
    'BIF',
    'BMD',
    'BND',
    'BOB',
    'BRL',
    'BSD',
    'BTN',
    'BWP',
    'BYR',
    'BZD',
    'CAD',
    'CDF',
    'CHF',
    'CLP',
    'CNH',
    'CNY',
    'COP',
    'CRC',
    'CUP',
    'CVE',
    'CYP',
    'CZK',
    'DEM',
    'DFL',
    'DJF',
    'DKK',
    'DKR',
    'DMM',
    'DOP',
    'DZD',
    'ECU',
    'EEK',
    'EGP',
    'ERN',
    'ETB',
    'EUR',
    'FFR',
    'FJD',
    'FKP',
    'FRF',
    'GBP',
    'GCH',
    'GEL',
    'GGP',
    'GHC',
    'GHS',
    'GIP',
    'GMD',
    'GNF',
    'GRD',
    'GTQ',
    'GYD',
    'HKD',
    'HNL',
    'HRK',
    'HTG',
    'HUF',
    'IDR',
    'ILS',
    'IMP',
    'INR',
    'IQD',
    'IRR',
    'ISK',
    'JEP',
    'JMD',
    'JOD',
    'JPY',
    'KES',
    'KGS',
    'KHR',
    'KMF',
    'KPW',
    'KRW',
    'KWD',
    'KYD',
    'KZT',
    'LAK',
    'LBP',
    'LIT',
    'LKR',
    'LRD',
    'LSL',
    'LTL',
    'LUF',
    'LVL',
    'LYD',
    'MAD',
    'MDL',
    'MGA',
    'MKD',
    'MMK',
    'MNT',
    'MOP',
    'MRO',
    'MTL',
    'MUR',
    'MVR',
    'MWK',
    'MXN',
    'MXP',
    'MYR',
    'MZM',
    'MZN',
    'NAD',
    'NGN',
    'NIO',
    'NOK',
    'NPR',
    'NZD',
    'OMR',
    'PAB',
    'PEN',
    'PGK',
    'PHP',
    'PKR',
    'PLN',
    'PTA',
    'PTE',
    'PYG',
    'QAR',
    'RBL',
    'ROL',
    'RON',
    'RSD',
    'RUB',
    'RUR',
    'RWF',
    'SAR',
    'SBD',
    'SCR',
    'SDD',
    'SEK',
    'SGD',
    'SHP',
    'SIT',
    'SKK',
    'SKR',
    'SLL',
    'SOS',
    'SPL',
    'SRD',
    'STD',
    'SVC',
    'SYP',
    'SZL',
    'THB',
    'TJS',
    'TMM',
    'TND',
    'TOP',
    'TRY',
    'TTD',
    'TVD',
    'TWD',
    'TZS',
    'UAH',
    'UGX',
    'USD',
    'UYP',
    'UYU',
    'UZS',
    'VEB',
    'VND',
    'VUV',
    'WST',
    'XAF',
    'XAG',
    'XAU',
    'XCD',
    'XDR',
    'XOF',
    'XPD',
    'XPF',
    'XPT',
    'YER',
    'ZAR',
    'ZMK',
  ];

  dbrsRating = [
    'AAA',
    'AA(H)',
    'AA',
    'AA(L)',
    'A(H)',
    'A',
    'A(L)',
    'BBB(H)',
    'BBB',
    'BBB(L)',
    'BB(H)',
    'BB',
    'BB(L)',
    'B(H)',
    'B',
    'B(L)',
    'CCC(H)',
    'CCC',
    'CCC(L)',
    'CC(H)',
    'CC',
    'CC(L)',
    'C(H)',
    'C',
    'C(L)',
    'D',
    'NA',
    'NR',
  ];

  dealIdentifier = ['sf', 'corporate'];

  dealOptions = [
    'absAssetClass',
    'assetClass',
    'bookManagerBankIds',
    'collateral',
    'countryIds',
    'countryIdsExclude',
    'couponGte',
    'couponLte',
    'couponType',
    'couponTypeExclude',
    'coveredBonds',
    'coveredBondsExclude',
    'currency',
    'currencyExclude',
    'dateOfferedGte',
    'dateOfferedLte',
    'dealIdentifier',
    'dealOriginatorIds',
    'dealType',
    'dealTypeExclude',
    'distributionStatistics',
    'emergingMarket',
    'emergingMarketExclude',
    'esgSriDealType',
    'euRiskRetentionCompliant',
    'fitchRating',
    'fromVolumeReport',
    'industryIds',
    'industryIdsExclude',
    'issuerIds',
    'marketType',
    'marketTypeExclude',
    'maturityGte',
    'maturityLte',
    'moodysRating',
    'rating',
    'ratingExclude',
    'relatedStories',
    'selfLed',
    'sfReportCategory',
    'sfReportType',
    'spRating',
    'status',
    'stsCompliant',
    'subordinatedHybridPreferred',
    'subordinatedHybridPreferredExclude',
    'term',
    'termExclude',
    'usRiskRetentionCompliant',
  ];

  dealType = [
    'Senior',
    'Senior unsecured',
    'Senior secured',
    'Secured',
    'Senior non-preferred',
    'Green Bond',
    'Social Bond',
    'Sustainability Bond',
    'Sustainability-Linked Bond',
    'ESG/SRI Other',
    'M&A',
    'Senior OpCo',
    'Senior HoldCo',
    'Holdco',
    'REIT',
    'Reverse Yankee',
    'Senior sub',
    'Junior sub',
    'PIK',
    'Discount',
    'Toggle',
    'FMB',
    '2nd Lien',
    'Other HY',
    'Sukuk',
    'ECoop',
    'BABs',
    'Debut',
  ];

  displayCurrency = ['Deal Currency', 'USD', 'EUR'];

  esgSriDealType = [
    'Green Bond',
    'Social Bond',
    'Sustainability Bond',
    'Sustainability-Linked Bond',
    'ESG/SRI Other',
  ];

  fdicGgb = [
    'All',
    'FDIC',
    'UK',
    'Australia',
    'Austria',
    'Denmark',
    'France',
    'Germany',
    'German Laender',
    'Greece',
    'Ireland',
    'Italy',
    'Korea',
    'Netherlands',
    'New Zealand',
    'Portugal',
    'Slovenia',
    'Spain',
    'Sweden',
    'Multi-jurisdiction',
    'Other',
  ];

  fitchRating = [
    'AAA',
    'AA+',
    'AA',
    'AA-',
    'A+',
    'A',
    'A-',
    'BBB+',
    'BBB',
    'BBB-',
    'BB+',
    'BB',
    'BB-',
    'B+',
    'B',
    'B-',
    'CCC+',
    'CCC',
    'CCC-',
    'CC',
    'C',
    'F-1+',
    'NA',
    'NR',
    'SD/D',
  ];

  fitchOutlook = [
    'Developing',
    'Evolving Watch',
    'Negative',
    'Negative Watch',
    'Positive',
    'Positive Watch',
    'Stable',
  ];

  format = [
    'Public',
    'Private',
    '144a W/ Reg Rights',
    '144a W/O Reg Rights',
    'Reg S/144a',
    'Reg S',
    'SEC Registered',
  ];

  governingLaw = [
    'Dutch',
    '100K',
    '100K&100K',
    '100K&1K',
    '10K',
    '1K',
    '1K&10K&100K',
    '1K&1K',
    '1K, 10K & 100K',
    '1M&10K',
    '1M&1M',
    '200K',
    '2K&1K',
    '500K',
    '50K&50K',
    '50k&50K',
    '5K',
    'ACT',
    'According to Programme',
    'Armenian',
    'Australian',
    'Austria',
    'Austrian',
    'Austrian Pfandbrief Act',
    'Belgian',
    'Belgian',
    'Belgian Pandbrieven',
    'Belgian covered bonds law',
    'Belgium',
    'Bristish Columbia and Canada',
    'British Columbia and Canada',
    'British Columbia and federal',
    'California',
    'Canada',
    'Canada and Quebec',
    'Canada, Province of Ontario',
    'Canadian',
    'Czech',
    'Danish',
    'Danish English Covered Bond',
    'Danish covered bond',
    'Delaware',
    'Dutch',
    'Dutch',
    'Dutch, CACs',
    'ENGLISH',
    'ENGLISH',
    'Engish',
    'England',
    'England and New South Wales',
    'English',
    'English',
    'English & Australia',
    'English & Danish',
    'English & Dubai',
    'English & Malaysian',
    'English & Norwegian',
    'English & Qatar',
    'English & Qatari',
    'English & Saudi',
    'English & Spanish',
    'English & Swedish',
    'English & Swiss',
    'English & UAE',
    'English Law',
    'English and Abu Dhabi',
    'English and Belgian',
    'English and DIFC',
    'English and Danish',
    'English and Dubai',
    'English and Dubai',
    'English and Emirate of Dubai',
    'English and Finnish',
    'English and French',
    'English and Hong Kong',
    'English and Italian',
    'English and Malaysian',
    'English and Norway',
    'English and Norwegian',
    'English and Qatar law',
    'English and Qatari',
    'English and Saudi',
    'English and Spanish',
    'English and Swedish',
    'English and Turkish',
    'English and UAE',
    'English and UK Covered bond',
    'English law',
    'English law',
    'English, Courts of England',
    'English, Dubai',
    'English, Dubai, UAE',
    'English, Indonesia',
    'English, Norwegian',
    'English, Portuguese',
    'English, Spanish',
    'English, Swedish',
    'English, UAE',
    'English, UAE, RAK',
    'English-Spanish',
    'English.',
    'English/ Singapore',
    'English/ Swiss',
    'English/Belgian',
    'English/Bermudan',
    'English/Danish',
    'English/Dutch/Spanish',
    'English/French',
    'English/HK',
    'English/Hong Kong',
    'English/Indonesian',
    'English/Irish for guarantee',
    'English/Irish/Swiss',
    'English/Italian',
    'English/Korean',
    'English/Macau',
    'English/Nigerian',
    'English/Norweigian',
    'English/Singapore',
    'English/Spanish',
    'English/Swedish',
    'English/Swiss',
    'English/Turkish',
    'Enlgish',
    'Federal Republic of Germany',
    'Fench',
    'Finish',
    'Finland',
    'Finnish',
    'France',
    'French',
    'French',
    'German',
    'German',
    'German law',
    'German, Austrian',
    'German, Duesseldorf',
    'German.',
    'German/Austrian',
    'Germanu',
    'Germany',
    'Gerrman',
    'HK',
    'HK law',
    'HONG KONG',
    'HONG KONG',
    'Hing Kong',
    'Hk',
    'Hong Kong',
    'Hong Kong',
    'Hong Kong Law',
    'Hong Kong, Gtee French law',
    'Hpmg Kong',
    'India',
    'Indiana',
    'Indonesian',
    'Irish',
    'Italian',
    'Italian',
    'Italian Covered Bond',
    'Italian Covered Bond',
    'Italian Covered Bond Law',
    'Italian covered bond',
    'Italy',
    'JAPAN',
    'Japan',
    'Japanese',
    'Japn',
    'Jersey',
    'London',
    'London and Dubai',
    'Luxembourg',
    'Luxembourg & Austria',
    'Luxembourg/English',
    'MSW',
    'Malaysia',
    'Malaysian',
    'Manitoba & Canada',
    'Manitoba & Canadian Federal',
    'Manitoba and Canadian',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Munich',
    'NSE',
    'NSW',
    'NSW',
    'NSW law',
    'NY',
    'NY state',
    'NZ',
    'Natherlands',
    'Netherland',
    'Netherlands',
    'Netherlands',
    'Netherlands law',
    'New South Wales',
    'New South Wales',
    'New Yiork',
    'New York',
    'New York',
    'New York law',
    'New York, Switzerland',
    'New Zealand',
    'Norway',
    'Norwegian',
    'Norwegian',
    'Ontario',
    'Ontario & Canada',
    'Ontario and Canada',
    'Ontario and Canadian',
    'Ontario, Canada',
    'Ontario/Canada',
    'PRC',
    'Pennsylvania',
    'Peruvian',
    'Portugal',
    'Portugese',
    'Portuguese',
    'Province of Ontario',
    'Province of Ontario & Canada',
    'QLD',
    'Quebec',
    'Quebec & Canada',
    'Quebec & Canadian',
    'Quebec, Canada',
    'Quebec/Canadian',
    'Queensland',
    'Queensland',
    'Queesland',
    'SINGAPORE',
    'SINGAPORE',
    'SWISS',
    'Scottish',
    'Sinagpore',
    'Singapore',
    'Singapore',
    'Singapore Law',
    'Singapore law',
    'Slovak',
    'Slovenian',
    'Spain',
    'Spanish',
    'Spanish',
    'Spanish and English',
    'Spanish legislative Covered',
    'Spanish, English',
    'State Of Georgia',
    'State Of Michigan',
    'State of NY, USA law',
    'State of Queensland',
    'Sweden',
    'Swedish',
    'Swedish/English',
    'Swedish; English',
    'Swiss',
    'Swiss',
    'Swiss/French',
    'Swss',
    'TAS',
    'Thai',
    'Thailand',
    'The Fiscal Agency',
    'Turkish/English',
    'UAE',
    'UK',
    'UK & Norway',
    'UK & Swedish',
    'UK (bonds)/Swiss (guarantee)',
    'UK, Denmark',
    'UK, Norway',
    'US',
    'US ( Illinois)',
    'US (Illinois)',
    'United Kingdom',
    'VIC',
    'VIC law',
    'Vic',
    'Victoria',
    'Victorian',
    'Vienna',
    'WA',
    'as per EMTCN programme',
    'as per EMTN',
    'as per EMTN programme',
    'english',
    'new York',
    'nz',
    'singapore',
    'singapore',
  ];

  indexLinked = [
    'HCPI',
    'CPI France',
    'CPI Greece',
    'CPI Italy',
    'RPI UK',
    'Other',
  ];

  jcrRating = [
    'AAA',
    'AA+',
    'AA',
    'AA-',
    'BBB+',
    'BBB',
    'BBB-',
    'BB+',
    'BB',
    'BB-',
    'B+',
    'B',
    'B-',
    'CCC',
    'CC',
    'C',
    'D',
    'NA',
    'NR',
  ];

  leagueOptions = [
    'absAssetClass',
    'assetClass',
    'bookManagerBankIds',
    'collateral',
    'countryIds',
    'countryIdsExclude',
    'couponGte',
    'couponLte',
    'couponType',
    'couponTypeExclude',
    'coveredBonds',
    'coveredBondsExclude',
    'currency',
    'currencyExclude',
    'dateOfferedGte',
    'dateOfferedLte',
    'dealIdentifier',
    'dealOriginatorIds',
    'dealType',
    'dealTypeExclude',
    'displayCurrency',
    'emergingMarket',
    'emergingMarketExclude',
    'fitchRating',
    'fromVolumeReport',
    'industryIds',
    'industryIdsExclude',
    'issuerIds',
    'marketType',
    'marketTypeExclude',
    'maturityGte',
    'maturityLte',
    'moodysRating',
    'rating',
    'ratingExclude',
    'selfLed',
    'sfReportCategory',
    'sfReportType',
    'spRating',
    'subordinatedHybridPreferred',
    'subordinatedHybridPreferredExclude',
    'term',
    'termExclude',
    'topTwentyOnly',
  ];

  listing = [
    '0.325',
    '500K&1K',
    '500k/1k',
    'ABM Oslo',
    'AIAF',
    'AIAF (Madrid)',
    'ASX',
    "Abidjan (Cote D'Ivoire)",
    'Amsterdam',
    'Amsterdam & Luxembourg',
    'Amsterdam, Frankfurt, Lux',
    'Amsterdam, London',
    'Amsterdam, Luxembourg',
    'Amsterdam/Luxembourg',
    'Armenia',
    'Athens',
    'Australia',
    'Australia Securities Exchange',
    'Australian',
    'Bank of Spain',
    'Barcelona',
    'Barcelona, Iberclear',
    'Belgium',
    'Berlin',
    'Berlin and Frankfurt',
    'Berlin, Frankurt, Hamburg',
    'Berlin-Bremen',
    'Bolsa de Bilbao',
    'Borsa Italiana',
    'Bratislava',
    'Brussels',
    'Bruxelles',
    'CABE',
    'CADE',
    'CISE',
    'CNMV',
    'CNMV and AIAF',
    'Cade',
    'Channel Island',
    'Copenhagan',
    'Copenhagen',
    'DEFX',
    'DIFX',
    'Deuda Publica',
    'Deuda Publica',
    'Douala, BVMAC',
    'Dubai',
    'Dubai Financial Market',
    'Dubai and Ireland',
    'Dublin',
    'Dublin & Frankfurt',
    'Dublin (Cloverie Notes)',
    'Dublin, Euronext',
    'Dublin, Frankfurt',
    'Duesseldorf',
    'Duesseldorf & Frankfurt',
    'Duesseldorf and Frankfurt',
    'Duesseldorf, Frankfurt',
    'Duesseldorf, Frankfurt, Munich',
    'Duesseldorf/Frankfurt',
    'Dusseldorf',
    'EMTF',
    'EMTF Luxembourg',
    'EUROMTF',
    'Easynext',
    'English',
    'Eurnonext, Amsterdam',
    'Euro MTF',
    'Euro MTF Market',
    'Euro MTF, Luxembourg',
    'EuroMTF',
    'Euronext',
    'Euronext',
    'Euronext - Amsterdam',
    'Euronext - Paris',
    'Euronext Amsterdam',
    'Euronext Amsterdam',
    'Euronext Amsterdam, Luxembourg',
    'Euronext Brussels',
    'Euronext Lisbon',
    'Euronext Paris',
    'Euronext Paris',
    'Euronext and Lisbon',
    'Euronext, Amsterdam',
    'Euronext, Lisbon',
    'Euronext, Paris',
    'Euronext-Amsterdam',
    'Euronext-Paris',
    'Euronext-Paris',
    'Euronext-Paris, Luxembourg',
    'Euronext/Frankfurt/Lux',
    'France',
    'Frankfurt',
    'Frankfurt & Euronext Amsterdam',
    'Frankfurt & Hamburg',
    'Frankfurt & Hannover',
    'Frankfurt & Luxembourg',
    'Frankfurt and Duesseldorf',
    'Frankfurt and Hamburg',
    'Frankfurt and Hannover',
    'Frankfurt and Luxembourg',
    'Frankfurt, Dublin',
    'Frankfurt, Hamburg',
    'Frankfurt, Hannover',
    'Frankfurt, Luxembourg',
    'Frankfurt, Munich',
    'Frankfurt, Paris, Vienna',
    'Frankfurt, Stuttgart',
    'Frankfurt/Main',
    'Frankfurt/Paris/Vienna',
    'Frankurt',
    'GTSM',
    'GTSM',
    'HK',
    'HK & London',
    'HK/Malaysia/Dubai',
    'HKE',
    'HKEX',
    'HKEx',
    'HKSE',
    'HKSE & SGX',
    'Hamburg',
    'Hamburg & Frankfurt',
    'Hamburg and Frankfurt',
    'Hamburg, Frankfurt',
    'Hannover',
    'Hannover & Frankfurt',
    'Hannover Stock Exchange',
    'Hannover, Frankfurt',
    'Hanover',
    'Helsinki',
    'Hki',
    'Hong Kong',
    "Hong Kong & Labuan Int'l FX",
    'Hong Kong, Malaysia',
    'Hong kong',
    'ISE',
    'Ireland',
    'Ireland',
    'Ireland & Ghana',
    'Ireland & Nasdaq Dubai',
    'Ireland and Dubai',
    'Ireland/Ghana',
    'Irish',
    'Irish SE',
    'Irish Stock Exchange',
    'Italy',
    'Japan',
    'KASE',
    'LSE',
    'Lisbon',
    'Lisbon Euronext',
    'Lisbon/Portugal',
    'Lixembourg',
    'Ljubljana',
    'London',
    'London',
    'London & Amsterdam',
    'London & Bursa Malaysia',
    'London & DFM',
    'London & Euronext',
    'London & Euronext',
    'London & Lux',
    'London & NY',
    'London (PSM)',
    'London PSM',
    'London Stock Exchange',
    'London and Amsterdam',
    'London and Kazakhstan',
    'London, Amsterdam',
    'London, Bucharest',
    'London, Dubai, Malaysia',
    'London, Euronext',
    'London, Euronext Amsterdam',
    'London, Frankfurt & Amsterdam',
    'London, Kazakhstan',
    'London, Luxembourg',
    'London/ORB',
    'Lonon',
    'Lonson',
    'Luixembourg',
    'Lux',
    'Lux / Euro MTF',
    'Lux, Euro MTF',
    'Lux/Paris',
    'Luxebourg',
    'Luxemborug, Stuttgart',
    'Luxemboug',
    'Luxemboug and Frankfurt',
    'Luxemboug, Euro MTF',
    'Luxembourg',
    'Luxembourg',
    'Luxembourg & Beirut',
    'Luxembourg & Beruit',
    'Luxembourg & Brussels',
    'Luxembourg & Euronext Paris',
    'Luxembourg & Euronext-Paris',
    'Luxembourg & Frankfurt',
    'Luxembourg & London',
    'Luxembourg & New York',
    'Luxembourg & Paris',
    'Luxembourg & Portal',
    'Luxembourg & Vienna',
    'Luxembourg EMTF',
    'Luxembourg Euro MTF',
    'Luxembourg EuroMTF',
    'Luxembourg MTF',
    'Luxembourg and Amsterdam',
    'Luxembourg and Dubai',
    'Luxembourg and Frankfurt',
    'Luxembourg and Italy',
    'Luxembourg and London',
    'Luxembourg and Paris',
    'Luxembourg and Stuttgart',
    'Luxembourg and Vienna',
    'Luxembourg, Euro MTF',
    'Luxembourg, AIAF',
    'Luxembourg, Amsterdam',
    'Luxembourg, Austria',
    'Luxembourg, Beirut',
    'Luxembourg, Borsa Italiana',
    'Luxembourg, Buenos Aires',
    'Luxembourg, EMTF',
    'Luxembourg, Euro MTF',
    'Luxembourg, EuroMTF',
    'Luxembourg, Euronext Brussels',
    'Luxembourg, Euronext Paris',
    'Luxembourg, Euronext-Brussels',
    'Luxembourg, Frank Furt',
    'Luxembourg, Frankfurt',
    'Luxembourg, London',
    'Luxembourg, Munich',
    'Luxembourg, Paris',
    'Luxembourg, Stuttgart',
    'Luxembourg, Vienna',
    'Luxembourg/Dubai',
    'Luxembourg/Euronext Paris',
    'Luxembourg/Frankfurt',
    'Luxembourg/London',
    'Luxemnbourg',
    'Luxwembourg',
    'MARF',
    'MOT',
    'MTS',
    'Madrid',
    'Madrid AIAF',
    'Milan',
    'Multiple',
    'Munich',
    'NASDAQ',
    'NASDAQ Dubai',
    'NASDAQ Dubai & Luxembourg',
    'NASDAQ OMX Copenhagen',
    'NASDAQ OMX Stockholm',
    'NSW',
    'NSX',
    'NYSE',
    'NYSE Euronext Amsterdam',
    'NZ',
    'NZDX',
    'NZX',
    'Nasdaq OMX',
    'Nasdaq OMX Helsinki',
    'Nasdaq OMX Helsinki',
    'Nasdaq OMX Stockholm',
    'New York',
    'OMX Helsinki',
    'OMX Stockholm',
    'OSE',
    'Olso',
    'Ontario & Canada',
    'Oslo',
    'PSM',
    'Paris',
    'Paris & Lux',
    'Paris & Luxembourg',
    'Paris Euronext',
    'Paris and Luxembourg',
    'Paris, Frankfurt, Vienna',
    'Paris, Luxembourg',
    'Paris, Luxembourg, Frankfurt',
    'Paris/Luxembourg',
    'Peru',
    'Prague',
    'Public Debt Market',
    'Public Debt Market',
    'Publica en Anotaciones',
    'SEHK',
    'SFX-ST',
    'SGX',
    'SGX',
    'SGX & Bursa',
    'SGX & Bursa Malaysia',
    'SGX & GTSM',
    'SGX and Frankfurt',
    'SGX and LFX',
    'SGX-ST',
    'SGX-ST',
    'SGX/LFX',
    'SIX',
    'SIX',
    'SIX, Amsterdam',
    'SIX, KASE',
    'SP',
    'SWX',
    'SXW',
    'Singapore',
    'Singapore',
    'Singapore Stock Exchange',
    'Singapore and ASX',
    'Singapore and Luxembourg',
    'Singapore/LFX',
    'Singapore/Luxembourg',
    'Singpaore',
    'Singpapore',
    'Singpore',
    'Stockholm',
    'Stockholm Nasdaq OMX',
    'Stuttgart',
    'Stuttgart',
    'Stuttgart + Luxembourg',
    'Stuttgart Stock Exchange',
    'Stuttgart and Luxembourg',
    'Stuttgart, Luxembourg',
    'Switzerland',
    'TBMA',
    'TMBA',
    'Tel Aviv',
    'Thai Bond Market Association',
    'ThaiBMA',
    'UK',
    'UK, LA',
    'UKLA',
    'UKLA London',
    'UKLA&LSE',
    'UKLA, London',
    'UNLISTED',
    'US/UK/Norway/EEA limits',
    'US92911HAA59',
    'Unisted',
    'United Kingdom',
    'Unlisted',
    'Unlisted',
    'Vienna',
    'Vienna & Luxembourg',
    'Vienna, Frankfurt and Paris',
    'Vienna, Frankfurt, Paris',
    'Vienna, Luxembourg',
    'Vienna, Third Market',
    'Vienna, second market',
    'ZSE',
    'Zurich',
    'lisbon',
    'luxembourg',
    'multiple',
    'singapore',
    'six',
    'unlisted',
  ];

  market = ['US', 'Euro', 'Global', 'Asia'];

  marketType = [
    'Yankee',
    'Swiss Foreign',
    'Samurai',
    'Uridashi',
    'Kangaroo',
    'Kauri',
    'Maple',
    'Japan Domestic',
    'Aussie Domestic',
    'HK Domestic',
    'Singapore Domestic',
    'Korea Domestic',
    'China Domestic',
    'Formosa',
    'Panda',
    'Dim Sum',
    'Komodo',
    'Masala',
  ];

  moodysOutlook = [
    'Developing',
    'Downgrade Watch',
    'Negative',
    'Positive',
    'Stable',
    'Uncertain Watch',
    'Upgrade Watch',
  ];

  moodysRating = [
    'P-1',
    'Aaa',
    'Aa1',
    'Aa2',
    'Aa3',
    'A1',
    'A2',
    'A3',
    'Baa1',
    'Baa2',
    'Baa3',
    'Ba1',
    'Ba2',
    'Ba3',
    'B1',
    'B2',
    'B3',
    'Caa1',
    'Caa2',
    'Caa3',
    'Ca',
    'C',
    'NA',
    'NR',
  ];

  payment = ['Annually', 'Monthly', 'Quarterly', 'Semi-Annually'];

  period = ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Annually'];

  proceedsCategory = [
    'Cash Distribution to Shareholders',
    'GCP',
    'Leveraged Buyout',
    'Merger and Acquistion',
    'Not Specified',
    'Refinance Bank Debt',
    'Refinance Debt Securities',
    'Other',
  ];

  rating = [
    'Investment grade',
    'High Yield',
    'Split Rated',
    'Not Rated',
    'N.A.',
  ];

  riRating = [
    'AAA',
    'AA+',
    'AA',
    'AA-',
    'BBB+',
    'BBB',
    'BBB-',
    'BB+',
    'B',
    'B-',
    'CCC+',
    'CCC',
    'CCC-',
    'CC+',
    'CC',
    'CC-',
    'C',
    'NA',
    'NR',
  ];

  securities = [
    'Adjustable Rate Capital Securities (ACTS)',
    'Asset-Backed Securities',
    'Auction-Rate Preferred Stock',
    'Baby Bonds',
    'Bank Notes',
    'Basket C Hybrid Subordinated Notes',
    'Benchmark Notes',
    'Beneficial Unsecured Securities (BLUS)',
    'Bonds',
    'Bullet Notes (Lower Tier II)',
    'Callable/ Redeemable Notes',
    'Canada Mortgage Bond (CMB)',
    'Canadian Originated Preferred Securities (COPRS)',
    'Capital Efficient Notes (Hybrid)',
    'Capital Securities',
    'Catastrophe Bonds',
    'Cedulas Hipotecarias',
    'Certificates of Deposit',
    'Certified Emission Reduction linked Uridashi bond',
    'Chase Extendible Remarketable Securities (CHEERS)',
    'Collateral Trust Bonds',
    'Collateralized Bond Obligation',
    'Collateralized Debt Obligation',
    'Collateralized Loan Obligation',
    'Collateralized Mortgage Obligation',
    'Commercial Mortgage Pass-Through Securities',
    'Commercial Mortgage-Backed Securities',
    'Cooperative FRN',
    'Covered Bonds',
    'Covered Floating Rate Euronotes',
    'Cumulative Exchangeable Redeemable Preferred Stock',
    'Dealer Remarketable Securities (DRS)',
    'Debentures',
    'Deposit Notes',
    'Domestic Eurobonds',
    'EARN',
    'EDP Servico Universal',
    'Enhanced Equipment Trust Securities (EETC)',
    'Enhanced Junior Subordinated Notes (Basket C Hybrid)',
    'Enhanced Trust Preferred Securities',
    'Equipment Trust Securities (ETC)',
    'Eurobonds',
    'Eurodollar',
    'Exercisable Put Option Securities (X-POS)',
    'Extendible Securities',
    'First & Refunding Mortgage Bonds',
    'First Mortgage Bonds',
    'First and Refunding Mortgage Floating-Rate Notes',
    'Fixed Rate CD Bank Notes',
    'Fixed Rate Covered Bond',
    'Fixed Rate Domestic Notes',
    'Fixed Rate Euronotes',
    'Fixed-Rate Adjustable Preferred Securities (FRAPS)',
    'Floating & Fixed Rate Preferred Securities (FRAPS)',
    'Floating Interest-Rate Subordinated Term Securities (FIRSTS)',
    'Floating Rate CD Bank Notes',
    'Floating Rate Domestic Notes',
    'Floating Rate Euronotes',
    'Floating Rate Notes',
    'Floating rate sukuk',
    'Floating-Rate Accrual Notes (FRAN)',
    'Floating-Rate Adjustable Preferred Securities (FRAPS)',
    'Floating-Rate TLGs',
    'General & Refunding Bonds',
    'General Obligation Taxable Municipal Bonds',
    'Global Bank Floating-Rate Notes',
    'Global Benchmark Bonds',
    'Global Bonds',
    'Global Floating-Rate TLGs',
    'Global Medium-Term Notes',
    'Global TLGs',
    'Government Guaranteed Notes',
    'Guaranteed Secured Index-Linked Bonds',
    'High Yield Trust Offered Preferred Securities (HYTOPS)',
    'Hybrid Adjustable-Rate Preferred Securities',
    'Hybrid CENTS (Capital Efficient Notes)',
    'Hybrid Capital Securities',
    'Hybrid Enhanced Junior Subordinated Debentures',
    'Hybrid Enhanced Junior Subordinated Notes',
    'Hybrid Enhanced Trust Preferred Securities',
    'Hybrid Enhanced Trust Preferred Securities (TRUPS)',
    'Hybrid Equity Capitalization Notes',
    'Hybrid Floating-Rate Notes (Upper Tier II)',
    'Hybrid Global Bonds (Lower Tier II)',
    'Hybrid Global Perpetual Notes (Tier I)',
    'Hybrid Global Perpetual Subordinated Preferred Step-Up Securities',
    'Hybrid Junior Subordinated Debentures',
    'Hybrid Junior Subordinated Debentures (Basket D)',
    'Hybrid Junior Subordinated Notes',
    'Hybrid Non-Cumulative Perpetual Preferred Securities',
    'Hybrid Non-Cumulative Perpetual Preferred Securities (Tier I)',
    'Hybrid Non-Voting Non-Cumulative Perpetual Preferred Securities',
    'Hybrid Notes',
    'Hybrid Notes (Lower Tier II)',
    'Hybrid Perpetual Benchmark Notes (Tier I)',
    'Hybrid Perpetual Global Bonds (Upper Tier II)',
    'Hybrid Perpetual Income Trust Securities',
    'Hybrid Perpetual Non-Cumulative Preference Stock',
    'Hybrid Perpetual Non-Cumulative Preferred Exchangeable Securities',
    'Hybrid Perpetual Non-Cumulative Preferred Securities',
    'Hybrid Perpetual Notes',
    'Hybrid Perpetual Notes (Tier I)',
    'Hybrid Perpetual Preferred Securities',
    'Hybrid Perpetual Preferred Securities (Tier I)',
    'Hybrid Perpetual Preferred Shares',
    'Hybrid Perpetual Preferred Step-Up Securities',
    'Hybrid Perpetual Preferred Subordinated Securities',
    'Hybrid Perpetual REIT Preferred Securities',
    'Hybrid Perpetual Securities',
    'Hybrid Perpetual Securities (Tier 1)',
    'Hybrid Perpetual Step-up Notes',
    'Hybrid Preferred Perpetual Non-Cumulative Preference Shares',
    'Hybrid Preferred Securities',
    'Hybrid Securities',
    'Hybrid Senior Insured Preferred Notes',
    'Hybrid Step-Up Notes',
    'Hybrid Step-up Subordinated Debentures',
    'Hybrid Subordinated Notes',
    'Hybrid Subordinated Notes (Lower Tier II)',
    'Hybrid Subordinated Unsecured Notes (Lower Tier II)',
    'Hybrid Tier I Preference Shares',
    'Hybrid Trust Preferred Fixed to Floating WITS',
    'Hybrid Trust Preferred Securities',
    'Hybrid Trust Preferred Securities (TRUPS)',
    'Hypothekenpfandbrief',
    'Index Amortizing Notes (IAN)',
    'Inflation-Linked',
    'Inhaberschuldverschreibungen',
    'Insured Quarterly Notes (IQ Notes)',
    'Jumbo Mortgage Pfandbrief',
    'Jumbo Notes',
    'Jumbo Public-Sector Pfandbrief',
    'Junior Maturing Principal Securities (JUMPS)',
    'Junior Subordinated Preferred Securities',
    'Kangaroo',
    'Kauri Bonds',
    'Landesschatzanweisungen',
    'LeasePlan Nederland N.V.',
    'Liquid Yield Option Notes (LYONS)',
    'Loan Participation Notes',
    'Mandatory Par Put Remarketable Securities (MOPPRS)',
    'Mandatory Putable Remarketable Securities (MAPS)',
    'Market Variable Putable Securities (MVPS)',
    'Medium-Term Floating-Rate Notes',
    'Medium-Term Notes',
    'Monthly Income Debt Securities (MIDS)',
    'Monthly Income Preferred Securities (MIPS)',
    'Mortgage Bonds',
    'Mortgage Pfandbrief',
    'Mortgage-Backed Pass-Through Securities',
    'Mortgage-Backed Securities',
    'Municipal Fund Term Preferred Shares',
    'Notes',
    'Notes (1st Lien)',
    'Obbligazioni Garantite',
    'Obligation Fonciere',
    'Obrigacoes Hipotecarias',
    'Pass-Through Asset Trust Securities (PATS)',
    'Pass-Through Securities',
    'Pay-In-Kind (PIK) Notes',
    'Pay-In-Kind (PIK) Preferred Securities',
    'Perpetual Capital Securities',
    'Perpetual Depositary Preferred Shares',
    'Perpetual Eurobonds',
    'Perpetual Non-Cumulative Preferred Securities',
    'Perpetual Notes',
    'Perpetual Preferred Securities',
    'Perpetual Subordinated Notes',
    'Pfandbrief',
    'Preferred Redeemable Increased Dividend Income Securities (PRIDES)',
    'Preferred Stock',
    'Preferred Subordinated Securities',
    'Premium Equity Participation Securities (PEPS)',
    'Price Efficient Par Put Remarketable Securities (PEPPERS)',
    'Private Institutional Trust Securities (PRINTS)',
    'Public Bonds',
    'Public Income Notes (PINES)',
    'Public Sector Pfandbriefe',
    'Putable Automatic Rate Reset Securities (PARRS)',
    'Putable Reset Securities (PURS)',
    'Quarterly Income Capital Securities (QUICS)',
    'Quarterly Income Debt Securities (QUIDS)',
    'Quarterly Income Preferred Securities (QUIPS)',
    'Quarterly Interest Bonds (QUIBS)',
    'Redeemable and Putable Securities (RAPS)',
    'Reference Notes',
    'Remarketable Or Redeemable Securities (ROARS)',
    'Remarketable Par Securities (ROPES)',
    'Reset Asset Capital Securities (RACS)',
    'Reset Put Securities (REPS)',
    'Rising Interest Subordinated Redeemable Securities (RISRS)',
    'Samurai',
    'Secured Lease Obligation Bonds (SLOBs)',
    'Securities of Deposit',
    'Senior Discount Notes',
    'Senior Eurobonds',
    'Senior Floating-Rate Toggle Notes',
    'Senior Notes',
    'Senior Notes',
    'Senior Notes (2nd lien)',
    'Senior Notes (holdco)',
    'Senior Secured Discount Notes',
    'Senior Secured Notes',
    'Senior Secured Toggle Notes',
    'Senior Subordinated Notes',
    'Senior Toggle Notes',
    'Senior Unsecured Notes',
    'Spread Adjusted Notes (SPANS)',
    'Step-Up Notes',
    'Step-Up Premium Rate (SUPeR) Preferred Stock',
    'Step-Up Real Estate Investment Trust Securities (STREITS)',
    'Stock Appreciation Income Linked Securities (SAILS)',
    'Structured Dutch Covered Bonds',
    'Student Loans Interest Margin Securities (SLIMS)',
    'Subordinated (Lower Tier II) Notes',
    'Subordinated (Upper Tier II) Notes',
    'Subordinated Bank Notes',
    'Subordinated Capital Income Securities (SKIS)',
    'Subordinated Notes',
    'TLGs',
    'Taxable Bonds',
    'Tercas (Cassa di Risparmio della Provincia di Teramo SpA)',
    'Term Enhanced Remarketable Securities (TERMS)',
    'Toggle',
    'Trust Exchangeable Preferred Shares (TRUEPRS)',
    'Trust Issued Preferred Securities (TIPS)',
    'Trust Originated Preferred Securities (TOPRS)',
    'Trust Preferred Perpetual Securities',
    'Trust Preferred Securities (TRUPS)',
    'UK RPI index-linked notes',
    'Uridashi',
    'Valley Inflation Indexed Power Securities (VIIPS)',
  ];

  sfReportCategory = ['Total SF', 'By Asset Class', 'By ABS Asset Class'];

  sfReportType = ['All Deals', 'Placed Deals'];

  spOutlook = [
    'Developing',
    'Downgrade Watch',
    'Negative',
    'Positive',
    'Stable',
    'Uncertain Watch',
    'Upgrade Watch',
  ];

  spRating = [
    'AAA',
    'AA',
    'AA+',
    'AA-',
    'A',
    'A+',
    'A -',
    'BBB',
    'BBB+',
    'BBB-',
    'BB',
    'BB+',
    'BB-',
    'B',
    'B+',
    'B-',
    'CCC',
    'CCC+',
    'CCC-',
    'CC',
    'C',
    'NA',
    'NR',
    'SD/D',
    'A-1+',
  ];

  status = [
    'Rumor',
    'Filing',
    'Mandate/Announcement',
    'Roadshow/Investor Call',
    'Price Talk/Guidance',
    'Launched',
    'Priced',
    'Postponed',
    'Withdrawn',
  ];

  usRiskRetentionCompliant = ['Yes', 'No', 'N/A'];
  euRiskRetentionCompliant = ['Yes', 'No', 'N/A'];
  stsCompliant = ['Yes', 'No', 'N/A'];

  // Dont change these without accounting for it in the deal migration
  subordinatedHybridPreferred = [
    'Subordinated',
    'Hybrid',
    'Corp Hybrid',
    'Preferred - cumulative',
    'Preferred - non-cumulative',
    'CoCo',
    'AT1',
    'Tier 1',
    'Tier 2',
    'Upper Tier 2',
    'Lower Tier 2',
    'Tier 3',
    '$25 Par Preferred',
    '$25 Sub Notes',
    '$1000 Par Preferred',
    '$1000 Sub Notes',
    'Restricted Tier 1',
  ];

  topTwentyChoice = ['Top 20', 'All Managers'];

  volumeReportAdvancedOptions = [
    'bookManagerBankIds',
    'countryIds',
    'countryIdsExclude',
    'couponType',
    'couponTypeExclude',
    'coveredBonds',
    'coveredBondsExclude',
    'dealType',
    'dealTypeExclude',
    'emergingMarket',
    'emergingMarketExclude',
    'fitchRating',
    'industryIds',
    'industryIdsExclude',
    'issuerIds',
    'marketType',
    'marketTypeExclude',
    'maturityGte',
    'maturityLte',
    'moodysRating',
    'rating',
    'ratingExclude',
    'spRating',
    'subordinatedHybridPreferred',
    'subordinatedHybridPreferredExclude',
    'term',
    'termExclude',
  ];

  volumeReportOptions = [
    'bookManagerBankIds',
    'canExport',
    'currency',
    'contentType',
    'countryIds',
    'countryIdsExclude',
    'couponType',
    'couponTypeExclude',
    'coveredBonds',
    'coveredBondsExclude',
    'dateOfferedGte',
    'dateOfferedLte',
    'dealIdentifier',
    'dealType',
    'dealTypeExclude',
    'destinations',
    'format',
    'esgSriDealType',
    'displayCurrency',
    'emergingMarket',
    'emergingMarketExclude',
    'fitchRating',
    'industryIds',
    'industryIdsExclude',
    'industryTable',
    'issuerIds',
    'marketType',
    'marketTypeExclude',
    'maturityGte',
    'maturityLte',
    'moodysRating',
    'period',
    'rating',
    'ratingExclude',
    'selfLed',
    'sendInCSV',
    'sendInExcel',
    'sendInXLSX',
    'sfReportCategory',
    'sfReportType',
    'spRating',
    'subordinatedHybridPreferred',
    'subordinatedHybridPreferredExclude',
    'term',
    'termExclude',
    'title',
  ];
}
